version: "3.1"

services:
  generator:
    image: my-registry:5500/aspnetcore-gen:ci-${GENERATOR_BUILD_NUMBER-30}
    ports:
      - "${PORT_GENERATOR-8081}:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAILHOG-8082}:8025"
  integration:
    image: my-registry:5500/aspnetcore-gen:integration-${BUILD_NUMBER-14}
    build: .
    environment:
      - Aspnetcore_Generator_Api
