version: "3.1"

services:
  generator:
    image: my-registry:5500/aspnetcore-gen:ci-${GENERATOR_BUILD_NUMBER-17}
    #ports:
    # - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
    #- "8025:8025"
  integration:
    image: my-registry:5500/aspnetcore-gen:integration-${BUILD_NUMBER-17}
    build: .
    environment:
      - TEAMCITY_PROJECT_NAME
